language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.0
    - php: hhvm
      env:
        - COLLECT_COVERAGE=false
  fast_finish: true


install:
  - travis_retry composer install --prefer-dist

script:
  - if [ "$COLLECT_COVERAGE" != "false" ]; then phpunit; fi
  - if [ "$EXECUTE_CS_CHECK" == "true" ]; then vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
